name: Test

on:
  push:
    branches:
      - '*'
    tags-ignore:
      - '*'
  pull_request:
    branches:

jobs:
  test:
    if: "!contains(toJson(github.event.commits), '[skip ci]')"
    strategy:
      matrix:
        node-version: [12.x, 14.x, 16.x]
        ts-version: [4.4.x, 4.5.x]
        axios-version: ['0.24']

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }} & Typescript ${{ matrix.ts-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - run: |
          yarn install
          yarn add typescript@${{ matrix.ts-version }} axios@${{ matrix.axios-version }} --dev
      - run: yarn test
      - name: Upload Coverage
        uses: actions/upload-artifact@v2
        if: github.ref == 'refs/heads/master'
        with:
          name: coverage
          path: coverage
  coverage:
    if: github.ref == 'refs/heads/master'
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Download Coverage
        uses: actions/download-artifact@v2
        with:
          name: coverage
          path: coverage
      - uses: codecov/codecov-action@v1
