name: Test

on:
  push:
    branches:
      - '*'
    tags-ignore:
      - '*'
  pull_request:
    branches:

jobs:
  type-checking:
    if: "!contains(toJson(github.event.commits), '[skip ci]')"
    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]
        ts-version: [5.0.x, 5.1.x, 5.2.x, 5.3.x, 5.4.x, 5.5.x]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
      - name: Use Node.js ${{ matrix.node-version }} & Typescript ${{ matrix.ts-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'
      - run: |
          pnpm install
          pnpm add typescript@${{ matrix.ts-version }} -D
      - run: pnpm tsc

  test:
    if: "!contains(toJson(github.event.commits), '[skip ci]')"
    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'
      - run: pnpm install
      - run: pnpm test
      - name: Upload Coverage
        if: github.ref == 'refs/heads/master' && strategy.job-index == 0
        uses: codecov/codecov-action@v3
        with:
          verbose: true
          fail_ci_if_error: true
